In [1]:
%matplotlib inline

In [156]:
import tensorflow as tf
import numpy as np

### Constant

In [11]:
c = tf.constant('Ala')
with tf.Session() as sess:
    output = sess.run(c)
    print output
    

Ala


### Placeholder

In [14]:
x = tf.placeholder(tf.int32)
with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 123})
    print output
    

123


### Add, multiply

In [37]:
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x,y), 1)
with tf.Session() as sess:
    output = sess.run([x,z])
    print output



[10, 4.0]


### Random initialization of variables

In [32]:
x = tf.Variable(tf.truncated_normal((5,5)))
y = tf.Variable(tf.zeros(5))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print sess.run(x), sess.run(y)

[[ 1.35927904  0.58119857 -0.24907777 -0.56299365 -0.65846711]
 [-1.33066416  0.11165965  1.40289247  0.22259471  0.70123672]
 [ 0.12581944 -0.62520164  0.23113443  0.12369755 -1.23400247]
 [-0.68802881  1.17237973  0.35626662  0.58347142 -1.08360183]
 [ 1.57960713  0.52056038 -0.0944941  -0.6722604   1.75073457]] [ 0.  0.  0.  0.  0.]


### Softmax

In [35]:
def run():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.placeholder(tf.float32)
    
    # TODO: Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)
    
    with tf.Session() as sess:
        # TODO: Feed in the logit data
        output = sess.run(softmax, feed_dict={logits: logit_data})

    return output

run()

array([ 0.65900117,  0.24243298,  0.09856589], dtype=float32)

### Cross entropy

If your label vector is [0, 0, 0, 1, 0] and the predicted probabilities are [0.27, 0.11, 0.33, 0.10, 0.19], what is the cross entropy?

In [41]:
softmax_data = [0.27, 0.11, 0.33, 0.10, 0.19]
one_hot_data = [0., 0., 0., 1, 0.]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

# TODO: Print cross entropy from session
with tf.Session() as sess:
    output = sess.run(cross_entropy, feed_dict={softmax : softmax_data, one_hot: one_hot_data})
    print output

2.30259


### Relu

In [9]:
output = None
hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[1.0, 2.0, 3.0, 4.0], [-1.0, -2.0, -3.0, -4.0], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model
o1 = tf.nn.relu(tf.add(tf.matmul(features, weights[0]), biases[0]))
output = tf.add(tf.matmul(o1, weights[1]), biases[1])

# TODO: Print session results
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    output = sess.run(output)
    print(output)

[[  5.11000013   8.44000053]
 [  0.           0.        ]
 [ 24.01000214  38.23999786]]


### Save restore

In [126]:
save_file = 'save.example.ckpt'
def save():
    tf.reset_default_graph()
    weights = tf.Variable(tf.truncated_normal([2, 3]), name='w')
    bias = tf.Variable(tf.truncated_normal([3]), name = 'b')

    # Class used to save and/or restore Tensor Variables
    saver = tf.train.Saver()
    print('Load Weights: {}'.format(weights.name))
    print('Load Bias: {}'.format(bias.name))

    
    with tf.Session() as sess:
        # Initialize all the Variables
        sess.run(tf.global_variables_initializer())

        # Show the values of weights and bias
        print('Weights:')
        print(sess.run(weights))
        print('Bias:')
        print(sess.run(bias))

        # Save the model
        saver.save(sess, save_file)

def restore():
    tf.reset_default_graph()
    # Two Variables: weights and bias
    bias = tf.Variable(tf.truncated_normal([3]), name ='b')
    weights = tf.Variable(tf.truncated_normal([2, 3]), name ='w')

    # Class used to save and/or restore Tensor Variables
    saver = tf.train.Saver()
    print('Load Weights: {}'.format(weights.name))
    print('Load Bias: {}'.format(bias.name))

    with tf.Session() as sess:
        # Load the weights and bias
        saver.restore(sess, save_file)

        # Show the values of weights and bias
        print('Weight:')
        print(sess.run(weights))
        print('Bias:')
        print(sess.run(bias))

In [127]:
save()

Load Weights: w:0
Load Bias: b:0
Weights:
[[ 1.13761497  0.68037736  0.33832976]
 [ 0.26226428  1.31909072 -0.70875919]]
Bias:
[-0.30559087  0.51383621 -1.46978426]


In [128]:
restore()

Load Weights: w:0
Load Bias: b:0
INFO:tensorflow:Restoring parameters from save.example.ckpt
Weight:
[[ 1.13761497  0.68037736  0.33832976]
 [ 0.26226428  1.31909072 -0.70875919]]
Bias:
[-0.30559087  0.51383621 -1.46978426]


### Dropout

In [153]:
# Solution is available in the other "solution.py" tab
tf.reset_default_graph()
hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[0.0, 2.0, 3.0, 4.0], [0.1, 0.2, 0.3, 0.4], [11.0, 12.0, 13.0, 14.0]])

keep_prob = tf.placeholder(tf.float32)
# TODO: Create Model with Dropout
o1 = tf.add(tf.matmul(features, weights[0]), biases[0])
o1 = tf.nn.relu(o1)
o1 = tf.nn.dropout(o1, keep_prob)
o2 = tf.add(tf.matmul(o1, weights[1]), biases[1])            

# TODO: Print logits from a session
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    for i in range(5):
        print (s.run(o1, feed_dict={keep_prob : 0.5}))
    


[[  0.           9.39999962   0.        ]
 [  1.12000012   0.           0.        ]
 [ 47.19999695   0.           0.        ]]
[[ 11.           0.           0.        ]
 [  0.           0.           1.0200001 ]
 [ 47.19999695   0.          48.20000076]]
[[  0.           9.39999962   0.        ]
 [  1.12000012   0.98000008   0.        ]
 [ 47.19999695  47.79999924   0.        ]]
[[  0.           0.           0.        ]
 [  1.12000012   0.98000008   0.        ]
 [ 47.19999695  47.79999924  48.20000076]]
[[ 11.           0.           9.39999962]
 [  0.           0.98000008   1.0200001 ]
 [ 47.19999695  47.79999924   0.        ]]


### Convolution

In [167]:
# `tf.nn.conv2d` requires the input be 4D (batch_size, height, width, depth)
# (1, 4, 4, 1)
x = np.array([
    [0, 1, 0.5, 10],
    [2, 2.5, 1, -8],
    [4, 0, 5, 6],
    [15, 1, 2, 3]], dtype=np.float32).reshape((1, 4, 4, 1))
X = tf.constant(x)


def conv2d(input):
    # Filter (weights and bias)
    # The shape of the filter weight is (height, width, input_depth, output_depth)
    # The shape of the filter bias is (output_depth,)
    # TODO: Define the filter weights `F_W` and filter bias `F_b`.
    # NOTE: Remember to wrap them in `tf.Variable`, they are trainable parameters after all.
    F_W = tf.Variable(tf.random_normal([3,3,1,3]))
    F_b = tf.Variable(tf.random_normal([3]))
    # TODO: Set the stride for each dimension (batch_size, height, width, depth)
    strides = [1, 1, 1, 1]
    # TODO: set the padding, either 'VALID' or 'SAME'.
    padding = 'VALID'
    # https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#conv2d
    # `tf.nn.conv2d` does not include the bias computation so we have to add it ourselves after.
    return tf.nn.conv2d(input, F_W, strides, padding) + F_b

out = conv2d(X)
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    print(s.run(out))

[[[[-10.64977169   1.47594523  -5.56974363]
   [ 22.27747154   3.51205277   2.96138167]]

  [[ -6.89210224   8.42251968  -8.22075462]
   [-32.23711777  -2.02499413  -6.45855093]]]]


### Maxpooling

In [168]:
# `tf.nn.max_pool` requires the input be 4D (batch_size, height, width, depth)
# (1, 4, 4, 1)
x = np.array([
    [0, 1, 0.5, 10],
    [2, 2.5, 1, -8],
    [4, 0, 5, 6],
    [15, 1, 2, 3]], dtype=np.float32).reshape((1, 4, 4, 1))
X = tf.constant(x)

def maxpool(input):
    # TODO: Set the ksize (filter size) for each dimension (batch_size, height, width, depth)
    ksize = [1, 2, 2, 1]
    # TODO: Set the stride for each dimension (batch_size, height, width, depth)
    strides = [1, 2, 2, 1]
    # TODO: set the padding, either 'VALID' or 'SAME'.
    padding = 'VALID'
    # https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#max_pool
    return tf.nn.max_pool(input, ksize, strides, padding)
    
out = maxpool(X)