In [1]:
import numpy as np

In [15]:
np.mean([1, 2, 3])

2.0

In [16]:
np.median([1,2,3,4,5])

3.0

In [17]:
np.median([1,2,3,4,5,6])

3.5

In [23]:
y_true = np.array([3, -0.5, 2, 7])
y_pred = np.array([2.5, 0.0, 2, 8])

In [24]:
np.var(y_true)

7.296875

In [25]:
np.var(y_true - y_pred)

0.3125

In [27]:
explained_variance = 1 - np.var(y_true - y_pred) / np.var(y_true)
explained_variance

0.95717344753747324

In [28]:
from sklearn.metrics import explained_variance_score

In [29]:
explained_variance_score(y_true, y_pred)

0.95717344753747324

### Order statistics
- amin(a[, axis, out, keepdims])	Return the minimum of an array or minimum along an axis.
- amax(a[, axis, out, keepdims])	Return the maximum of an array or maximum along an axis.
- nanmin(a[, axis, out, keepdims])	Return minimum of an array or minimum along an axis, ignoring any NaNs.
- nanmax(a[, axis, out, keepdims])	Return the maximum of an array or maximum along an axis, ignoring any NaNs.
- ptp(a[, axis, out])	Range of values (maximum - minimum) along an axis.
- percentile(a, q[, axis, out, ...])	Compute the qth percentile of the data along the specified axis.
- nanpercentile(a, q[, axis, out, ...])	Compute the qth percentile of the data along the specified axis, while ignoring nan values.

In [54]:
v, m = np.array([1,2,-1]), np.array([[1,2,-1], [4,5,6]])

In [48]:
np.amin(v)

-1

In [52]:
np.amin(m)

[1, 2, -1]

In [55]:
np.amin(m, axis=0), np.amin(m, axis=1)

(array([ 1,  2, -1]), array([-1,  4]))

In [59]:
np.amin([1,2,3, np.nan]), np.amax([1,2,3, np.nan])

(nan, nan)

In [60]:
np.nanmin([1,2,3, np.nan]), np.nanmax([1,2,3, np.nan])

(1.0, 3.0)

In [61]:
np.ptp(v)

3

In [62]:
np.ptp(m)

7

In [63]:
np.ptp(m, axis = 0), np.ptp(m, axis = 1)

(array([3, 3, 7]), array([3, 2]))

In [72]:
np.percentile(v, 50), np.percentile(v, 75)

(1.0, 1.5)

In [75]:
np.percentile(m, 50)

3.0

In [76]:
np.percentile(m, 50, axis = 0), np.percentile(m, 50, axis = 1)

(array([ 2.5,  3.5,  2.5]), array([ 1.,  5.]))

### Averages and variances
- median(a[, axis, out, overwrite_input, keepdims])	Compute the median along the specified axis.
- average(a[, axis, weights, returned])	Compute the weighted average along the specified axis.
- mean(a[, axis, dtype, out, keepdims])	Compute the arithmetic mean along the specified axis.
- std(a[, axis, dtype, out, ddof, keepdims])	Compute the standard deviation along the specified axis.
- var(a[, axis, dtype, out, ddof, keepdims])	Compute the variance along the specified axis.
- nanmedian(a[, axis, out, overwrite_input, ...])	Compute the median along the specified axis, while ignoring NaNs.
- nanmean(a[, axis, dtype, out, keepdims])	Compute the arithmetic mean along the specified axis, ignoring NaNs.
- nanstd(a[, axis, dtype, out, ddof, keepdims])	Compute the standard deviation along the specified axis, while ignoring NaNs.
- nanvar(a[, axis, dtype, out, ddof, keepdims])	Compute the variance along the specified axis, while ignoring NaNs.


In [92]:
m = np.array([[1,2,4], [4,5,7]])

In [93]:
print np.median(m), np.median(m, axis = 0), np.median(m, axis = 1)

4.0 [ 2.5  3.5  5.5] [ 2.  5.]


In [94]:
print np.mean(m), np.mean(m, axis = 0), np.mean(m, axis = 1)

3.83333333333 [ 2.5  3.5  5.5] [ 2.33333333  5.33333333]


In [95]:
print np.average(m), np.average(m, axis = 0), np.average(m, axis = 1)

3.83333333333 [ 2.5  3.5  5.5] [ 2.33333333  5.33333333]


In [99]:
print np.average(m, axis = 0, weights=[2,1]), np.average(m, axis = 1, weights=[3,2,1])

[ 2.  3.  5.] [ 1.83333333  4.83333333]


In [101]:
print np.std(m), np.var(m), np.sqrt(np.var(m))

1.95078331845 3.80555555556 1.95078331845


### Correlating
- corrcoef(x[, y, rowvar, bias, ddof])	Return Pearson product-moment correlation coefficients.
- corelate(a, v[, mode])	Cross-correlation of two 1-dimensional sequences.
- cov(m[, y, rowvar, bias, ddof, fweights, ...])	Estimate a covariance matrix, given data and weights.

In [ ]:
TODO

### Histograms
- histogram(a[, bins, range, normed, weights, ...])	Compute the histogram of a set of data.
- histogram2d(x, y[, bins, range, normed, weights])	Compute the bi-dimensional histogram of two data samples.
- histogramdd(sample[, bins, range, normed, ...])	Compute the multidimensional histogram of some data.
- bincount(x[, weights, minlength])	Count number of occurrences of each value in array of non-negative ints.
- digitize(x, bins[, right])	Return the indices of the bins to which each value in input array belongs.


In [118]:
h, edges = np.histogram([1,2,3,4,1,1], bins=3)

In [119]:
h, edges

(array([3, 1, 2]), array([ 1.,  2.,  3.,  4.]))